services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    ports:
      # AMQP 프로토콜 포트
      - '5672:5672'
      # 관리 UI 포트 (http://localhost:15672)
      - '15672:15672'
    volumes:
      - ./docker-data/rabbitmq/data:/var/lib/rabbitmq
      - ./docker-data/rabbitmq/log:/opt/custom/var/log
      - ./docker-data/rabbitmq:/etc/rabbitmq
      - ./docker-data/rabbitmq/stream:/var/lib/rabbitmq/stream
    networks:
      - app_network
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stream && rabbitmq-server && rabbitmq_mqtt && rabbitmq_management && rabbitmq_management_agent"

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker-data/redis/data:/data
      - ./docker-data/redis/log:/var/log/redis
      - ./docker-data/redis:/usr/local/etc/redis # Redis 설정 파일 마운트
    networks:
      - app_network

  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: mango
      MARIADB_DATABASE: mydb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - ./docker-data/mariadb/data:/var/lib/mysql # MariaDB 데이터 파일 저장
      - ./docker-data/mariadb:/etc/mysql # MariaDB 설정 파일 저장
      - ./docker-data/mariadb/log:/var/log/mysql # 로그 저장
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
